import clsx from "clsx";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Ingram, Pragmatica } from "@/assets/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="ru"
			className={clsx(
				"page _home _desktop",
				Ingram.variable,
				Pragmatica.variable
			)}
		>
			<head>
				<meta name="color-scheme" content="light dark" />
				<meta
					name="theme-color"
					content="#eee"
					media="(prefers-color-scheme: light)"
				/>
				<meta
					name="theme-color"
					content="#111213"
					media="(prefers-color-scheme: dark)"
				/>
			</head>
			<body className="page__body">
				<div className="page__wrapper">
					<Header />

					<main className="page__main">{children}</main>
				</div>
				<Footer />
			</body>
		</html>
	);
}
