import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru" className="page _home _desktop">
			<head>
				<meta name="color-scheme" content="light dark" />
				<meta
					name="theme-color"
					content="#eee"
					media="(prefers-color-scheme: light)"
				/>
				<meta
					name="theme-color"
					content="#111213"
					media="(prefers-color-scheme: dark)"
				/>

				<link
					rel="preload"
					href="/assets/fonts/pragmatica_book.woff2"
					as="font"
					type="font/woff2"
				/>
				<link
					rel="preload"
					href="/assets/fonts/pragmatica_medium.woff2"
					as="font"
					type="font/woff2"
				/>
			</head>
			<body className="page__body">
				<div className="page__wrapper">
					<Header />

					<main className="page__main">{children}</main>
				</div>
				<Footer />
			</body>
		</html>
	);
}
